helm:
  parameters:
  - name: image.name
    value: 911167924085.dkr.ecr.ap-northeast-2.amazonaws.com/forever-staging-registry
    forcestring: true
  - name: image.tag
    value: origin-staging-3-6ba1ce3
    forcestring: true
