image:
  repository: 911167924085.dkr.ecr.ap-northeast-2.amazonaws.com/forever_registry
  tag: latest

env:
  SPRING_DATASOURCE_URL: jdbc:mysql://dev-mysql-mysql.dev-mysql.svc.cluster.local:3306/forever_mysql_db
  SPRING_DATASOURCE_USERNAME: root

keda:
  enabled: false