image:
  repository: 911167924085.dkr.ecr.ap-northeast-2.amazonaws.com/forever_registry
  tag: stable

env:
  SPRING_DATASOURCE_URL: "jdbc:mysql://prod-db.example.com:3306/yourdb"
  SPRING_DATASOURCE_USERNAME: "prod-user"
