replicaCount: 8

image:
  name: 911167924085.dkr.ecr.ap-northeast-2.amazonaws.com/forever_dev_registry
  tag: latest
  pullPolicy: IfNotPresent

env:
  SPRING_DATASOURCE_URL: jdbc:mysql://dev-mysql-mysql.dev-mysql.svc.cluster.local:3306/forever_mysql_db
  SPRING_DATASOURCE_USERNAME: root
  SPRING_HIKARI_MAX_POOL_SIZE: "5"
  SPRING_HIKARI_MAX_IDLE: "2"
keda:
  enabled: false
