apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deployment.name }}
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.app.label }}
  template:
    metadata:
      labels:
        app: {{ .Values.app.label }}
      annotations: # 컨피그맵 변경을 감지하도록
        configmap-checksum: {{ include "fechart.configmap" . | sha256sum }}
    spec:
      containers:
        - name: {{ .Values.container.name }}
          image: {{ .Values.image.name }}:{{ .Values.image.tag }}
          ports:
            - containerPort: {{ .Values.container.port }}
          volumeMounts:
            - name: nginx-config-volume
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: default.conf
            - name: frontend-config-volume  
              mountPath: /usr/share/nginx/html/config.json
              subPath: config.json
      volumes:
        - name: nginx-config-volume
          configMap:
            name: {{ .Values.configMap.nginx.name }}  
            items:
              - key: default.conf
                path: default.conf
        - name: frontend-config-volume  
          configMap:
            name: {{.Values.configMap.vite.name}}  
