apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configMap.nginx.name }}
  namespace: {{ .Values.namespace }}
data:
  default.conf: |
    server {
        listen {{ .Values.configMap.nginx.server.listen }};
        server_name {{ .Values.configMap.nginx.server.server_name }};
        root {{ .Values.configMap.nginx.server.root }};

        location / {
            add_header Cache-Control "{{ .Values.configMap.nginx.locationRoot.cacheControl }}";
            try_files {{ .Values.configMap.nginx.locationRoot.try_files }};
        }

        location /api/v1/ {
            add_header Cache-Control "{{ .Values.configMap.nginx.locationApiV1.cacheControl }}";
            proxy_pass {{ .Values.configMap.nginx.locationApiV1.proxy_pass }};
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
