
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  namespace: {{ .Values.namespace}}
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-scheme: {{ .Values.service.annotations.loadBalancerScheme }}
spec:
  selector:
    app: {{ .Values.app.label }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
  type: {{ .Values.service.type }}