apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configMap.vite.name }}
  namespace: {{ .Values.namespace }}
data:
  config.json: |
    {
      "BASE_URL": "{{ .Values.configMap.vite.baseUrl }}"
    }
