replicaCount: 1
image:
  name: 911167924085.dkr.ecr.ap-northeast-2.amazonaws.com/forever_registry
  tag: latest
  pullPolicy: IfNotPresent

env:
  SPRING_DATASOURCE_URL: ""
  SPRING_DATASOURCE_USERNAME: "admin"
  SPRING_HIKARI_MAX_POOL_SIZE: "5"
  SPRING_HIKARI_MAX_IDLE: "2"

keda:
  enabled: false
