helm:
  parameters:
  - name: image.name
    value: 911167924085.dkr.ecr.ap-northeast-2.amazonaws.com/forever_dev_fe_registry
    forcestring: true
  - name: image.tag
    value: origin-develop-38-32aec4b
    forcestring: true
