helm:
  parameters:
  - name: image.name
    value: 911167924085.dkr.ecr.ap-northeast-2.amazonaws.com/forever_stag_fe_registry
    forcestring: true
  - name: image.tag
    value: origin-staging-8-1071e9f
    forcestring: true
