apiVersion: v1
kind: ConfigMap
metadata:
  name: "spring-app-config"
  namespace: {{ .Values.namespace}}
data:
  spring.datasource.url: {{ .Values.env.SPRING_DATASOURCE_URL}}
  spring.datasource.username: {{ .Values.env.SPRING_DATASOURCE_USERNAME}}
  spring.datasource.hikari.maximum-pool-size: {{.Values.env.SPRING_HIKARI_MAX_POOL_SIZE}}
  spring.datasource.hikari.minimum-idle: {{.Values.env.SPRING_HIKARI_MAX_IDLE}}