apiVersion: v1
kind: ConfigMap
metadata:
  name: "spring-app-config"
  namespace: {{ .Values.namespace}}
data:
  spring.datasource.url: {{ .Values.env.SPRING_DATASOURCE_URL}}
  spring.datasource.username: {{ .Values.env.SPRING_DATASOURCE_USERNAME}}
