apiVersion: v1
kind: ConfigMap
metadata:
  name: "spring-app-config"
  namespace: {{ .Values.namespace}}
data:
  spring.datasource.url: jdbc:mysql://forever-mysql-db.ctouy8o0uopm.ap-northeast-2.rds.amazonaws.com:3306/forever_mysql_db
  spring.datasource.username: admin
