apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  namespace: {{.Values.namespace}}
spec:
  selector:
    matchLabels:
      app: {{ .Values.appLabel }}
  # replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ .Values.appLabel }}
    spec:
      terminationGracePeriodSeconds: 60000
      serviceAccountName: {{ .Values.serviceAccount.name }}
      containers:
      - name: app
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        env:
        - name: SPRING_DATASOURCE_URL
          valueFrom:
            configMapKeyRef:
              name: {{ .Values.configMap.name }}
              key: spring.datasource.url
        - name: SPRING_DATASOURCE_USERNAME
          valueFrom:
            configMapKeyRef:
              name: {{ .Values.configMap.name }}
              key: spring.datasource.username
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Values.secret.name }}
              key: password
        ports:
        - containerPort: {{ .Values.container.port }}
