replicaCount: 3


namespace: "kafka-stream"

container:
  name: router-app
  # port: 8080



# configMap:
#   name: "spring-app-config"

# secret:
#   name: "spring-app-secret"
  

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: false
  automount: true
  annotations: {}
  name: "default" #default사용하다 추후 변경 예정

podAnnotations: {}
podLabels: {}
appLabel: "router-app"

podSecurityContext: {}

securityContext: {}
service:
  name: "router-app-service"
  protocol: "TCP"
  type: ClusterIP
  # port: 8080
  # targetPort: 8080

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []


resources: {}


livenessProbe:
  httpGet:
    path: /
    port: http
readinessProbe:
  httpGet:
    path: /
    port: http

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

volumes: []
# - name: foo
#   secret:
#     secretName: mysecret
#     optional: false

# Additional volumeMounts on the output Deployment definition.
volumeMounts: []
# - name: foo
#   mountPath: "/etc/foo"
#   readOnly: true

nodeSelector: {}

tolerations: []

affinity: {}
